### ISSUE TITLE
Saving settings on exit

### ISSUE THREAD

**Issue by NetBUG** [interrogator/corpkit#13]
When program exits, last user corpus path should be stored and loaded upon next start.

Possible improvements:
1. If two program launches result in crash, this value can be dropped.
2. Last few corpora used can be stored as "recent"

**Comment by interrogator** [comment]
@NetBUG I don't think I've yet hooked up any 'on exit' saving, but it shouldn't be too hard.

If you explicitly do 'Save project settings', and load it up again, do you get the correct corpus? 

Are you proposing a 'recent corpora' that behaves just like 'recent project'?

**Comment by interrogator** [comment]
I had a play around, and you're right, the current corpus wasn't being remembered, due to a silly mistake. Anyway, that should be fixed in 71210d0339b421a4dc3328b6f498ad38a7b0e998. There's also now a prompt to save project settings on quit, and tool preferences are auto-saved. I'm closing this issue, and the functionality will be in the next app build. Let me know if there's a problem.
