### ISSUE TITLE
coreNLP error

### ISSUE THREAD

**Issue by maiacjefferson** [interrogator/corpkit#28]
I've downloaded the standalone OSX corpkit app but I'm getting error messages that have to do with coreNLP. After creating a new project, opening it, and adding a corpus, I get the following message when I try to parse the corpus: "CoreNLP parser not found. Download/install it?". When I click "Yes", nothing happens and no download is initiated. I've tried downloading coreNPL separately and re-setting the CoreNLP path so as to make sure there are no mismatches, but when I try to change the path, I get a message that coreNLP has not been not found in the folder I selected that I know for sure contains coreNLP. Any thoughts on why I'm having these issues with coreNLP and corpkit?

**Comment by interrogator** [comment]
CoreNLP has been updated in the time since I wrote the downloader code. I'll investigate and let you know what I find.

**Comment by interrogator** [comment]
Also, if, after these errors, you can go to Help --> Save log, and if there's any error info in there, it would be very useful to post it here.

**Comment by interrogator** [comment]
I've had trouble reproducing the issue, but I found a little bug in that part of the code, which I've fixed. Hopefully that had something to do with it. Try redownloading.

Another thing you can try is making sure your path to CoreNLP looks like this:

`/Users/yourname/corenlp/stanford-corenlp-full-2015-12-09/stanford-corenlp-3.6.0.jar`

That's the default place that `corpkit` looks.

**Comment by decarvaj** [comment]
Thank you for your help with this, interrogator! I appreciate it!! I've tried redownloading the app, but now I can't even open it. The error message I get is as follows: "corpkit is damaged and can't be opened. You should move it to the Trash", with the only options being "cancel" or "Move to Trash".

**Comment by interrogator** [comment]
No problem. Hoping the tool can be useful, so any feedback I get is great.

That error message is something related to security in OSX—basically they want app developers to pay an annual fee to be ‘official’, which adds a certificate to the software that lets it open. It can be disabled:

https://www.yourkit.com/download/mountain_lion.html
http://www.tech-recipes.com/rx/45404/mac-downloaded-app-is-damaged-and-cant-be-opened-error-solved/

I have no idea why it appeared with the last version only.

By the way, I’m developing on El Capitan, so if you’re on Mountain Lion, that could be cause for some kind of incompatibility, though probably nothing major.

Let me know what happens if you can!

**Comment by interrogator** [comment]
No problem. Hoping the tool can be useful, so any feedback I get is great.

That error message is something related to security in OSX—basically they want app developers to pay an annual fee to be ‘official’, which adds a certificate to the software that lets it open. It can be disabled:

https://www.yourkit.com/download/mountain_lion.html
http://www.tech-recipes.com/rx/45404/mac-downloaded-app-is-damaged-and-cant-be-opened-error-solved/

I have no idea why it appeared with the last version only.

By the way, I’m developing on El Capitan, so if you’re on Mountain Lion, that could be cause for some kind of incompatibility, though probably nothing major.

Let me know what happens if you can!


On 2 Apr 2016, at 12:20 AM, decarvaj <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank you for your help with this, interrogator! I appreciate it!! I've tried redownloading the app, but now I can't even open it. The error message I get is as follows: "corpkit is damaged and can't be opened. You should move it to the Trash", with the only options being "cancel" or "Move to Trash".

**Comment by maiacjefferson** [comment]
I tried re-downloading it once again and the error message no longer cropped up. My operating system is also El Captain.

I've run a small-scale, preliminary analysis and I believe corpkit is now working for me. I think it is a phenomenal tool and I am really looking forward to using it to conduct my full corpus analysis.

Thank you so much for developing this and for your willingness to help.

**Comment by interrogator** [comment]
Thanks! I really appreciate the feedback. The functionality of the tool can respond to users' interests a bit (time permitting), so if you find there are things missing, things causing errors, and/or things without documentation, do just file another issue. I'm more than happy to help.
